export interface IMediaCard {
    adult: boolean,
    backdrop_path: string | null,
    id: number,
    name?: string,
    original_language: string,
    original_name?: string,
    title?: string,
    original_title?: string,
    overview: string,
    poster_path: string | null,
    media_type: string,
    genre_ids: number[],
    popularity: number,
    first_air_date?: string,
    release_date?: string,
    video?: boolean,
    vote_average: number,
    vote_count: number,
    origin_country?: string[],
}